# Generated by Django 5.2 on 2025-05-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincheck',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукты в заказе'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SH', 'Вызов из ресторана'), ('CR', 'Доставка курьером')], default='SH', max_length=2, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop_project.ProductInCheck', to='shop_project.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productincheck',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_project.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='productincheck',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_project.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productincheck',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_project.product', verbose_name='Продукт'),
        ),
    ]
