# Generated by Django 5.2 on 2025-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0002_alter_productincheck_options_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='summ',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
    ]
