# Generated by Django 5.2 on 2025-05-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0003_remove_order_summ_order_delivery_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.CharField(max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
